spring:
  application:
    name: version-api
  profiles:
    active: ${APP_PROFILE:dev}

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

app:
  version: ${APP_VERSION:1.0.0}
  environment: ${APP_ENVIRONMENT:local}

logging:
  config: classpath:log4j2.xml