# openshift/deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: intflow-service
  labels:
    app: intflow-service
    version: "${APP_VERSION}"
    environment: "${APP_ENVIRONMENT}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: intflow-service
  template:
    metadata:
      labels:
        app: intflow-service
        version: "${APP_VERSION}"
        environment: "${APP_ENVIRONMENT}"
    spec:
      containers:
        - name: intflow-service
          image: ${IMAGE_TAG}
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: APP_VERSION
              value: "${APP_VERSION}"
            - name: APP_ENVIRONMENT
              value: "${APP_ENVIRONMENT}"
            - name: SERVER_PORT
              value: "8080"
            - name: SPRING_PROFILES_ACTIVE
              value: "${APP_ENVIRONMENT}"
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1001
            capabilities:
              drop:
                - ALL
