apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: inflow-service
  labels:
    app: inflow-service
spec:
  host: inflow-service-${APP_ENVIRONMENT}.apps.crc.testing.com
  to:
    kind: Service
    name: intflow-service
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None